In [1]:
# install open3d by: conda install -c open3d-admin open3d
import open3d
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
df = pd.read_csv("data_examples/test_video/0000000_pointcloud.csv", header=None)
df.iloc[:, :3].to_csv("data_examples/test_video_mod/0000000_pointcloud.xyz", header=None, index=False, sep=" ")

In [3]:
# for creating xyzrgb format (r=intensity, g,b=0)
df2 = df.copy()
df2[3] = df2[3]/100
df2[4] = 0
df2[5] = 0

df2.to_csv("data_examples/test_video_mod/0000000_pointcloud.xyzrgb", header=None, index=False, sep=" ")
df2.head()

0    1    2     3  4  5
0  773 -221  426  0.25  0  0
1  769 -223  424  0.25  0  0
2  767 -225  424  0.25  0  0
3  765 -227  423  0.25  0  0
4  767 -231  424  0.25  0  0

In [4]:
pcd = open3d.read_point_cloud("data_examples/test_video_mod/0000000_pointcloud.xyzrgb")
pcd_pts = np.asarray(pcd.points)

In [5]:
print(pcd)

PointCloud with 37568 points.


In [6]:
print(pcd_pts)

[[ 773. -221.  426.]
 [ 769. -223.  424.]
 [ 767. -225.  424.]
 ...
 [ 319. -215.   20.]
 [ 319. -216.   20.]
 [ 319. -217.   20.]]


In [7]:
# open3d.draw_geometries([pcd])

In [8]:
downpcd = open3d.voxel_down_sample(pcd, voxel_size = 0.00001)
downpcd_pts = np.asarray(downpcd.points)

In [9]:
print(downpcd_pts)

[[  472.  -270.    20.]
 [ 3586. -1893.   796.]
 [ 1839.   642.    26.]
 ...
 [  344.   236.    11.]
 [  344.   234.    11.]
 [  319.  -215.    20.]]


In [10]:
# open3d.draw_geometries([downpcd])

In [11]:
df_pcd = pd.DataFrame(pcd_pts)
print("min points:")
print(df_pcd.min(axis=0))
print("\nmax points:")
print(df_pcd.max(axis=0))
# df_pcd.iloc[:, 0].hist()

min points:
0     319.0
1   -2128.0
2      -5.0
dtype: float64

max points:
0    9791.0
1    5643.0
2    1020.0
dtype: float64


In [12]:
df_dwn = pd.DataFrame(downpcd_pts).astype(int)
print("min points:")
print(df_dwn.min(axis=0))
print("\nmax points:")
print(df_dwn.max(axis=0))

min points:
0     319
1   -2128
2      -5
dtype: int32

max points:
0    9791
1    5643
2    1020
dtype: int32


In [13]:
pcd_pts.shape, downpcd_pts.shape
# some points were merged to same voxel.

((37568, 3), (37444, 3))