In [1]:
# install open3d by: conda install -c open3d-admin open3d
import open3d
import pandas as pd
import numpy as np

%matplotlib inline

### read pc and transform to format open3d knows to digest:

In [2]:
df = pd.read_csv("data_examples/test_video/0000000_pointcloud.csv", header=None)
df.iloc[:, :3].to_csv("data_examples/test_video_mod/0000000_pointcloud.xyz", header=None, index=False, sep=" ")

In [3]:
# for creating xyzrgb format (r=intensity, g,b=0)
df2 = df.copy()
df2[3] = df2[3]/100
df2[4] = 0. # df2[3]
df2[5] = df2[3]

df2.to_csv("data_examples/test_video_mod/0000000_pointcloud.xyzrgb", header=None, index=False, sep=" ")
df2.head()

0    1    2     3    4     5
0  773 -221  426  0.25  0.0  0.25
1  769 -223  424  0.25  0.0  0.25
2  767 -225  424  0.25  0.0  0.25
3  765 -227  423  0.25  0.0  0.25
4  767 -231  424  0.25  0.0  0.25

In [4]:
pcd = open3d.read_point_cloud("data_examples/test_video_mod/0000000_pointcloud.xyzrgb")
pcd_pts = np.asarray(pcd.points)

In [5]:
print(pcd)

PointCloud with 37568 points.


In [6]:
print(pcd_pts)

[[ 773. -221.  426.]
 [ 769. -223.  424.]
 [ 767. -225.  424.]
 ...
 [ 319. -215.   20.]
 [ 319. -216.   20.]
 [ 319. -217.   20.]]


In [7]:
open3d.draw_geometries([pcd])

### downsample to voxel-grid:

In [8]:
downpcd = open3d.voxel_down_sample(pcd, voxel_size = 100)
downpcd_pts = np.asarray(downpcd.points)

In [9]:
print(downpcd_pts)

[[ 2723.625      -1860.4375       767.        ]
 [ 1578.6         -733.26666667    68.        ]
 [ 2327.5         -607.33333333   169.66666667]
 ...
 [  517.52401747  -129.86317322    11.        ]
 [  417.96432111  -238.53716551    19.46481665]
 [  459.59259259   328.18518519    11.        ]]


In [10]:
open3d.draw_geometries([downpcd])

In [11]:
df_pcd = pd.DataFrame(pcd_pts)
print("min points:")
print(df_pcd.min(axis=0))
print("\nmax points:")
print(df_pcd.max(axis=0))
# df_pcd.iloc[:, 0].hist()

min points:
0     319.0
1   -2128.0
2      -5.0
dtype: float64

max points:
0    9791.0
1    5643.0
2    1020.0
dtype: float64


In [12]:
df_dwn = pd.DataFrame(downpcd_pts).astype(int)
print("min points:")
print(df_dwn.min(axis=0))
print("\nmax points:")
print(df_dwn.max(axis=0))

min points:
0     350
1   -2106
2      -5
dtype: int32

max points:
0    9791
1    5643
2    1019
dtype: int32


In [13]:
pcd_pts.shape, downpcd_pts.shape
# some points were merged to same voxel.

((37568, 3), (1301, 3))