In [1]:
# install open3d by: conda install -c open3d-admin open3d
import open3d
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
df = pd.read_csv("data_examples/test_video/0000000_pointcloud.csv", header=None)
df.iloc[:, :3].to_csv("data_examples/test_video_mod/0000000_pointcloud.xyz", header=None, index=False, sep=" ")

In [3]:
df.iloc[:, :3].head()

0    1    2
0  773 -221  426
1  769 -223  424
2  767 -225  424
3  765 -227  423
4  767 -231  424

In [4]:
pcd = open3d.read_point_cloud("data_examples/test_video_mod/0000000_pointcloud.xyz")
pcd_pts = np.asarray(pcd.points)/100

In [5]:
print(pcd)

PointCloud with 37568 points.


In [6]:
print(pcd_pts)

[[ 7.73 -2.21  4.26]
 [ 7.69 -2.23  4.24]
 [ 7.67 -2.25  4.24]
 ...
 [ 3.19 -2.15  0.2 ]
 [ 3.19 -2.16  0.2 ]
 [ 3.19 -2.17  0.2 ]]


In [7]:
# open3d.draw_geometries([pcd])

In [8]:
downpcd = open3d.voxel_down_sample(pcd, voxel_size = 1.)
downpcd_pts = np.asarray(downpcd.points)

In [9]:
print(downpcd_pts)

[[  767.  -225.   403.]
 [ 2683. -1871.   779.]
 [ 2880. -1893.   804.]
 ...
 [  319.  -215.    20.]
 [  319.  -216.    20.]
 [  319.  -217.    20.]]


In [10]:
# open3d.draw_geometries([downpcd])

In [11]:
df_pcd = pd.DataFrame(pcd_pts)
print("min points:")
print(df_pcd.min(axis=0))
print("\nmax points:")
print(df_pcd.max(axis=0))
# df_pcd.iloc[:, 0].hist()

min points:
0     3.19
1   -21.28
2    -0.05
dtype: float64

max points:
0    97.91
1    56.43
2    10.20
dtype: float64


In [12]:
df_dwn = pd.DataFrame(downpcd_pts).astype(int)
print("min points:")
print(df_dwn.min(axis=0))
print("\nmax points:")
print(df_dwn.max(axis=0))

min points:
0     319
1   -2128
2      -5
dtype: int32

max points:
0    9791
1    5643
2    1020
dtype: int32


In [13]:
pcd_pts.shape, downpcd_pts.shape
# some points were merged to same voxel.

((37568, 3), (37444, 3))