In [1]:
import pandas as pd
import numpy as np

import open3d
# examples/Python/Tutorial/Basic/icp_registration.py
    
from open3d import *
import numpy as np
import copy

In [2]:
path = "voxelling_output/submission_files/check_registration/"
pcw1 = pd.read_csv(path+"0000007_pointcloud.csv", header=None)
pcw2 = pd.read_csv(path+"0000020_pointcloud.csv", header=None)

pcw1.iloc[:, :3].to_csv(path+"source.xyz", sep=" ", header=None, index=None)
pcw2.iloc[:, :3].to_csv(path+"target.xyz", sep=" ", header=None, index=None)

In [3]:
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    draw_geometries([source_temp, target_temp])

In [4]:
source = read_point_cloud(path+"source.xyz")
target = read_point_cloud(path+"target.xyz")

In [5]:
source

PointCloud with 39281 points.

In [6]:
threshold = 1000000000000000000

trans_init = np.eye(4)
trans_init[:3, 3] = 100*np.random.rand(3)

# trans_init = np.array([[np.cos(np.pi/8), np.sin(np.pi/8), 0., 10.],
#                       [-np.sin(np.pi/8), np.cos(np.pi/8), 0., 20.],
#                       [0,0,1,10],
#                       [0,0,0,1]])
trans_init

array([[ 1.        ,  0.        ,  0.        , 66.46777295],
       [ 0.        ,  1.        ,  0.        , 48.00280859],
       [ 0.        ,  0.        ,  1.        , 63.09584695],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
draw_registration_result(source, target, trans_init)

In [8]:
print("Initial alignment")
evaluation = evaluate_registration(source, target,
        threshold, trans_init)
print(evaluation)

Initial alignment
RegistrationResult with fitness = 1.000000, inlier_rmse = 65.666740, and correspondence_set size of 39281
Access transformation to get result.


In [9]:
print("Apply point-to-point ICP")
reg_p2p = registration_icp(source, target, threshold, trans_init,
        TransformationEstimationPointToPoint(), )
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
print("")
draw_registration_result(source, target, reg_p2p.transformation)

Apply point-to-point ICP
RegistrationResult with fitness = 1.000000, inlier_rmse = 12.504035, and correspondence_set size of 39281
Access transformation to get result.
Transformation is:
[[ 9.99999688e-01  6.36826445e-04 -4.66460284e-04  2.76984209e+00]
 [-6.36661682e-04  9.99999735e-01  3.53284431e-04  1.99644116e+00]
 [ 4.66685141e-04 -3.52987343e-04  9.99999829e-01 -1.66867856e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]



In [12]:
R = reg_p2p.transformation
print(R)
print(R.shape)

[[ 9.99999688e-01  6.36826445e-04 -4.66460284e-04  2.76984209e+00]
 [-6.36661682e-04  9.99999735e-01  3.53284431e-04  1.99644116e+00]
 [ 4.66685141e-04 -3.52987343e-04  9.99999829e-01 -1.66867856e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
(4, 4)


-------------------------------

In [35]:
from utilities.math_utils import extract_rotation, extract_translation

In [36]:
rot = extract_rotation(R)
trans = extract_translation(R)
rot, trans

(array([-0.00035328, -0.00046646, -0.00063683]),
 array([ 2.76984209,  1.99644116, -1.66867856]))

---------------------------------------------

In [37]:
def rot_and_trans_mat_to_euler_3d(R):
    # based on rotation and translation matrix defenition found here: http://planning.cs.uiuc.edu/node104.html
    assert R[3,3]==1 and R.shape==(4,4) and R[3,1]==0
    x_t = R[0,3]
    y_t = R[1,3]
    z_t = R[2,3]
    beta = -np.arcsin(R[2,0])
    gamma = np.arcsin(R[2,1]/np.cos(beta))
    alpha = np.arcsin(R[1,0]/np.cos(beta))
    return (x_t, y_t, z_t), (alpha, beta, gamma)

In [38]:
trans, rot = rot_and_trans_mat_to_euler_3d(R)

In [39]:
rot, trans  ## looks like my function iz good but alpha and gamma should replace positions 

((-0.0006366617942376715, -0.00046668515798245963, -0.0003529873890561033),
 (2.769842092347897, 1.9964411649030667, -1.6686785648441038))

In [44]:
gt_ego1 = pd.read_csv(path+"0000007_egomotion.csv", header=None)
gt_ego2 = pd.read_csv(path+"0000020_egomotion.csv", header=None)
gt_ego1-gt_ego2

FileNotFoundError: File b'E:/Datasets/DataHack/Test/vid_21_estimate_egomotion0000007_egomotion.csv' does not exist

----------------------------------------

In [16]:
from glob import glob
import os
import open3d
from utilities.math_utils import extract_rotation, extract_translation
import numpy as np
import pandas as pd

path = "E:/Datasets/DataHack/Test/vid_21_estimate_egomotion"
trans_init = np.eye(4)
trans_init[:3, 3] = 100*np.random.rand(3)
threshold = 10000

pc_paths = glob(path+'/*pointcloud.csv')
xyz_paths = [i.replace('_pointcloud.csv', '.xyz') for i in pc_paths]

if not os.path.exists(xyz_paths[0]):
    for idx in range(len(pc_paths)):
        pc = pd.read_csv(pc_paths[idx], header=None)
        pc.iloc[:, :3].to_csv(xyz_path[idx], sep=" ", header=None, index=None)

pc_prev = open3d.read_point_cloud(xyz_paths[0])
R_prev = np.eye(4)
cur_ego = pd.DataFrame(np.zeros((1,6)), dtype=np.float)
print(cur_ego)

for xyz_path in xyz_paths[1:]:
    pc_cur = open3d.read_point_cloud(xyz_path)
    evaluation = open3d.evaluate_registration(pc_prev, pc_cur, threshold, trans_init)
    print("Apply point-to-point ICP to: \n{}".format(xyz_path))
    reg_p2p = open3d.registration_icp(pc_prev, pc_cur, threshold, trans_init,
            open3d.TransformationEstimationPointToPoint(), )
    print(reg_p2p)
    print("Transformation is:")
    R_cur = reg_p2p.transformation
    print(R_cur)
    R = np.matmul(R_cur, R_prev)
    rot = extract_rotation(R)
    trans = extract_translation(R)
    cur_ego.at[0, :2] = rot
    cur_ego.at[0, 3:] = trans
    print(cur_ego)
    print("")    
    
    cur_ego.iloc[0, :].T.to_csv(xyz_path.replace('.xyz', '_egomotion.csv'), sep=" ", header=None, index=None)
    R_prev = R
    pc_prev = pc_cur


     0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0
Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004001.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.988768, and correspondence_set size of 42987
Access transformation to get result.
Transformation is:
[[ 9.99999135e-01 -2.75508964e-04 -1.28624424e-03 -3.03663137e+01]
 [ 2.71744213e-04  9.99995682e-01 -2.92619085e-03 -9.76548338e-01]
 [ 1.28704487e-03  2.92583879e-03  9.99994891e-01 -3.65200365e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2          3         4       5
0  0.002926 -0.001286  0.000276 -30.366314 -0.976548 -0.3652

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004002.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.258841, and correspondence_set size of 43151
Access transformation to get result.
Transformation is:
[[ 9.99994562e-01 -1.06362065e-0

RegistrationResult with fitness = 1.000000, inlier_rmse = 19.975694, and correspondence_set size of 44140
Access transformation to get result.
Transformation is:
[[ 9.99999173e-01 -4.00345813e-04 -1.22179028e-03 -3.20475562e+01]
 [ 3.96854005e-04  9.99995840e-01 -2.85684863e-03 -3.64603021e-01]
 [ 1.22292892e-03  2.85636139e-03  9.99995173e-01 -5.05044265e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2           3          4          5
0  0.027698 -0.028169  0.002922 -433.615194 -19.632923 -30.094498

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004015.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.964282, and correspondence_set size of 44274
Access transformation to get result.
Transformation is:
[[ 9.99998974e-01  1.12828908e-04 -1.42837558e-03 -3.19114752e+01]
 [-1.16767713e-04  9.99996191e-01 -2.75775917e-03 -1.16529083e-01]
 [ 1.42805898e-03  2.75792312e-03  9.99995177e

RegistrationResult with fitness = 1.000000, inlier_rmse = 17.329157, and correspondence_set size of 45194
Access transformation to get result.
Transformation is:
[[ 9.99999297e-01  2.22600416e-04 -1.16487635e-03 -3.49623521e+01]
 [-2.26025868e-04  9.99995649e-01 -2.94130932e-03  5.26006184e-03]
 [ 1.16421654e-03  2.94157055e-03  9.99994996e-01 -4.00318905e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2           3          4        5
0  0.054711 -0.039635  0.004286 -826.780664 -27.405824 -52.0312

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004028.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 21.324341, and correspondence_set size of 45275
Access transformation to get result.
Transformation is:
[[ 9.99994296e-01 -2.43676761e-04 -3.36870995e-03 -3.32330079e+01]
 [ 2.43665032e-04  9.99999970e-01 -3.89219998e-06  9.71364737e-01]
 [ 3.36871080e-03  3.07134096e-06  9.99994326e-01 

RegistrationResult with fitness = 1.000000, inlier_rmse = 31.551607, and correspondence_set size of 46793
Access transformation to get result.
Transformation is:
[[ 9.99999470e-01 -6.38315377e-04  8.07384223e-04 -3.71650711e+01]
 [ 6.38295697e-04  9.99999796e-01  2.46323107e-05 -5.32084514e-01]
 [-8.07399782e-04 -2.41169478e-05  9.99999674e-01 -4.97183131e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3          4          5
0  0.079487 -0.05181  0.005996 -1230.634329 -20.010843 -76.981495

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004041.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 23.646126, and correspondence_set size of 46715
Access transformation to get result.
Transformation is:
[[ 9.99999416e-01  4.61422075e-05 -1.07974104e-03 -2.58731005e+01]
 [-4.87057991e-05  9.99997180e-01 -2.37435937e-03  9.09085645e-01]
 [ 1.07962844e-03  2.37441057e-03  9.99996598e

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004053.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 31.430956, and correspondence_set size of 49663
Access transformation to get result.
Transformation is:
[[ 9.99947011e-01  1.13840502e-03 -1.02312768e-02 -6.72051106e-01]
 [-1.16857481e-03  9.99994986e-01 -2.94328656e-03  4.46573796e+00]
 [ 1.02278748e-02  2.95508661e-03  9.99943327e-01 -3.43090534e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3         4           5
0  0.099094 -0.097949  0.007043 -1586.275014  4.685025 -165.260992

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004054.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 25.595498, and correspondence_set size of 50333
Access transformation to get result.
Transformation is:
[[ 9.99988730e-01 -1.11469858e-03 -4.61497331e-03 -2.66289847e+01]
 [ 1.10560017e-03

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004066.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 31.029680, and correspondence_set size of 49095
Access transformation to get result.
Transformation is:
[[ 9.99995697e-01  1.27689162e-03 -2.64128826e-03  1.34103021e+01]
 [-1.28510137e-03  9.99994342e-01 -3.10887646e-03  5.34217773e+00]
 [ 2.63730362e-03  3.11225740e-03  9.99991679e-01 -4.19743767e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3          4          5
0  0.116702 -0.098188  0.001471 -1580.480067  41.643518 -178.73391

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004067.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 27.883876, and correspondence_set size of 48954
Access transformation to get result.
Transformation is:
[[ 9.99995608e-01  1.64583944e-03 -2.46475437e-03  1.29135408e+01]
 [-1.65407606e-03

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004079.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.767641, and correspondence_set size of 46981
Access transformation to get result.
Transformation is:
[[ 9.99994675e-01 -1.20882923e-03  3.03140580e-03 -1.76697798e+01]
 [ 1.21689814e-03  9.99995718e-01 -2.66134346e-03 -1.67340098e+00]
 [-3.02817571e-03  2.66501820e-03  9.99991864e-01  1.19232305e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3         4           5
0  0.131279 -0.088912 -0.000754 -1576.686474  56.47948 -177.300283

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004080.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.701635, and correspondence_set size of 46774
Access transformation to get result.
Transformation is:
[[ 9.99993732e-01  1.27353145e-03 -3.30376576e-03  4.52894674e+00]
 [-1.28413009e-03

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004092.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.863336, and correspondence_set size of 47323
Access transformation to get result.
Transformation is:
[[ 9.99993707e-01  4.44580839e-04 -3.51978475e-03 -2.88256181e+01]
 [-4.45378069e-04  9.99999875e-01 -2.25718974e-04  4.78102070e-01]
 [ 3.51968396e-03  2.27285188e-04  9.99993780e-01 -2.57353256e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3          4           5
0  0.150324 -0.106452 -0.006899 -1760.841752  93.152357 -228.333042

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004093.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.810331, and correspondence_set size of 47598
Access transformation to get result.
Transformation is:
[[ 9.99994662e-01  8.28135692e-06 -3.26751189e-03 -3.57363499e+01]
 [-8.81953943e-

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004105.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 21.046606, and correspondence_set size of 50633
Access transformation to get result.
Transformation is:
[[ 9.99996517e-01  4.06625683e-04 -2.60799279e-03 -3.26849113e+01]
 [-3.97199896e-04  9.99993392e-01  3.61369259e-03  2.91385430e+00]
 [ 2.60944498e-03 -3.61264411e-03  9.99990070e-01 -1.62083380e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3          4          5
0  0.145056 -0.151265  0.000783 -2244.459324  93.256923 -340.20928

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004106.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 20.326383, and correspondence_set size of 50860
Access transformation to get result.
Transformation is:
[[ 9.99966339e-01  7.95893740e-03 -1.99391748e-03 -3.65607442e+01]
 [-7.95016158e-03

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004118.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.212461, and correspondence_set size of 51656
Access transformation to get result.
Transformation is:
[[ 9.99989058e-01  3.10040776e-03 -3.50318439e-03 -3.01479106e+01]
 [-3.10361073e-03  9.99994770e-01 -9.09235911e-04 -2.89558467e-01]
 [ 3.50034707e-03  9.20098483e-04  9.99993450e-01 -3.01357369e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3           4           5
0  0.131525 -0.192298 -0.091788 -2605.624017  351.935959 -436.243001

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004119.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.843745, and correspondence_set size of 51778
Access transformation to get result.
Transformation is:
[[ 9.99989868e-01  2.90353519e-03 -3.43993344e-03 -3.15176011e+01]
 [-2.90621346

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004131.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 17.812019, and correspondence_set size of 53793
Access transformation to get result.
Transformation is:
[[ 9.99959886e-01  8.94359272e-03  4.89310095e-04 -3.27028888e+01]
 [-8.94533209e-03  9.99953232e-01  3.67621407e-03  2.88378044e+00]
 [-4.56408649e-04 -3.68044364e-03  9.99993123e-01 -8.32572160e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3           4           5
0  0.128352 -0.230615 -0.119705 -2982.693874  450.697911 -561.973089

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004132.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 24.132715, and correspondence_set size of 53832
Access transformation to get result.
Transformation is:
[[ 9.99702777e-01  2.43532410e-02 -1.13001818e-03 -3.21750132e+01]
 [-2.43416878

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004144.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.176961, and correspondence_set size of 58345
Access transformation to get result.
Transformation is:
[[ 9.99478324e-01  3.21624972e-02 -2.94155226e-03 -3.42387282e+01]
 [-3.21736797e-02  9.99474929e-01 -3.83673750e-03 -1.39157319e+00]
 [ 2.81660867e-03  3.92937653e-03  9.99988313e-01 -7.64095929e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2            3            4           5
0  0.098524 -0.300335 -0.61908 -2708.780686  1736.337969 -488.068754

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004145.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.374577, and correspondence_set size of 58980
Access transformation to get result.
Transformation is:
[[ 9.99601387e-01  2.81799164e-02 -1.72014409e-03 -3.38303751e+01]
 [-2.81900784

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004157.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 21.636371, and correspondence_set size of 54395
Access transformation to get result.
Transformation is:
[[ 9.98819276e-01  4.84462708e-02 -3.60720279e-03 -2.11331326e+01]
 [-4.84579046e-02  9.98820065e-01 -3.21074925e-03  7.44326636e+00]
 [ 3.44739770e-03  3.38175573e-03  9.99988340e-01 -2.36629594e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.125895 -0.351131 -1.183089 -1757.847818  3098.478231 -754.971974

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004158.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.597303, and correspondence_set size of 53215
Access transformation to get result.
Transformation is:
[[ 9.98950041e-01  4.56554637e-02 -3.79385422e-03 -2.32028637e+01]
 [-4.566911

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004170.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.279868, and correspondence_set size of 46793
Access transformation to get result.
Transformation is:
[[ 9.99954684e-01  9.47416176e-03 -9.32873659e-04 -2.96917330e+01]
 [-9.47825281e-03  9.99945030e-01 -4.48327380e-03 -1.72550986e+00]
 [ 8.90347118e-04  4.49191265e-03  9.99989515e-01 -6.52102269e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         0        1         2            3            4           5
0 -0.16145 -0.33563 -1.507539 -1081.804016  3602.118605 -570.060468

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004171.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.818173, and correspondence_set size of 46643
Access transformation to get result.
Transformation is:
[[ 9.99963642e-01  8.47371681e-03 -9.53987773e-04 -2.83197266e+01]
 [-8.47791071e-

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004183.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.318009, and correspondence_set size of 45658
Access transformation to get result.
Transformation is:
[[ 9.99995733e-01  2.61324723e-03 -1.30555303e-03 -3.27161073e+01]
 [-2.61780557e-03  9.99990441e-01 -3.50208256e-03  3.36926868e+00]
 [ 1.29638874e-03  3.50548530e-03  9.99993015e-01 -1.35044786e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.133658 -0.340168 -1.575541 -1229.564496  3723.254205 -417.550911

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004184.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 26.424016, and correspondence_set size of 45600
Access transformation to get result.
Transformation is:
[[ 9.99996549e-01  2.31158959e-03 -1.24877835e-03 -3.14550760e+01]
 [-2.316309

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004196.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.488273, and correspondence_set size of 45137
Access transformation to get result.
Transformation is:
[[ 9.99998913e-01  1.47782964e-04 -1.46684402e-03 -2.64141104e+01]
 [-1.52956504e-04  9.99993767e-01 -3.52750199e-03  9.46271226e-01]
 [ 1.46631357e-03  3.52772252e-03  9.99992703e-01 -1.11266377e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.093308 -0.356362 -1.590315 -1510.881176  3767.430791 -284.566979

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004197.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.478031, and correspondence_set size of 45055
Access transformation to get result.
Transformation is:
[[ 9.99999047e-01  1.84635978e-04 -1.36827299e-03 -3.20283275e+01]
 [-1.891526

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004209.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.320406, and correspondence_set size of 42286
Access transformation to get result.
Transformation is:
[[ 9.99997615e-01  2.09431976e-03 -6.19187236e-04 -2.19983193e+01]
 [-2.09601534e-03  9.99994021e-01 -2.75055138e-03  3.77364551e+00]
 [ 6.13422999e-04  2.75184264e-03  9.99996026e-01 -8.00628030e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.049329 -0.374611 -1.598691 -1871.829658  3802.522851 -152.879499

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004210.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 30.667267, and correspondence_set size of 41848
Access transformation to get result.
Transformation is:
[[ 9.99990180e-01  2.49699894e-03 -3.66114177e-03 -3.46852501e+01]
 [-2.500002

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004222.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 48.141078, and correspondence_set size of 43412
Access transformation to get result.
Transformation is:
[[ 9.99985772e-01 -1.70152501e-03 -5.05577860e-03 -3.21352719e+01]
 [ 1.62834648e-03  9.99894365e-01 -1.44432657e-02 -9.02223411e+00]
 [ 5.07982011e-03  1.44348277e-02  9.99882909e-01 -2.00356074e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2          3            4          5
0 -0.000226 -0.402085 -1.596867 -2293.2907  3809.661649 -42.151703

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004223.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.065280, and correspondence_set size of 43693
Access transformation to get result.
Transformation is:
[[ 9.99998555e-01 -1.53250573e-03 -7.35347941e-04 -2.99231627e+01]
 [ 1.53071701e-03

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004235.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 17.129448, and correspondence_set size of 43827
Access transformation to get result.
Transformation is:
[[ 9.99998030e-01  1.76036697e-03 -9.16926421e-04 -3.28298855e+01]
 [-1.76308764e-03  9.99994021e-01 -2.97484856e-03  2.37406195e+00]
 [ 9.11684114e-04  2.97645932e-03  9.99995155e-01  1.83798126e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4          5
0  0.007477 -0.410609 -1.611641 -2494.157435  3867.506364 -17.143643

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004236.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 20.262257, and correspondence_set size of 43836
Access transformation to get result.
Transformation is:
[[ 9.99996591e-01  2.34786870e-03 -1.14287759e-03 -3.08050687e+01]
 [-2.35149015

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004248.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.097922, and correspondence_set size of 43112
Access transformation to get result.
Transformation is:
[[ 9.99999759e-01  5.68424901e-04 -3.98542849e-04 -3.22849385e+01]
 [-5.68762473e-04  9.99999479e-01 -8.47415254e-04  1.33104003e+00]
 [ 3.98060949e-04  8.47641726e-04  9.99999562e-01 -8.80596262e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0  0.055882 -0.426635 -1.605089 -2805.102231  3862.263376  104.605723

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004249.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 36.031764, and correspondence_set size of 42745
Access transformation to get result.
Transformation is:
[[ 9.99998820e-01 -1.52377421e-03 -1.97063800e-04 -3.33099480e+01]
 [ 1.523696

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004261.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 37.107878, and correspondence_set size of 39846
Access transformation to get result.
Transformation is:
[[ 9.99998227e-01  6.34680670e-04 -1.77288527e-03  1.67624104e+00]
 [-6.39873221e-04  9.99995503e-01 -2.92983980e-03  4.76977959e+00]
 [ 1.77101779e-03  2.93096903e-03  9.99994136e-01 -2.95211972e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         0         1        2            3            4          5
0  0.06418 -0.459274 -1.61723 -3073.515811  3940.211125  31.460213

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004262.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 39.318205, and correspondence_set size of 39876
Access transformation to get result.
Transformation is:
[[ 9.99998680e-01 -2.95302164e-04 -1.59749356e-03  1.37196629e+00]
 [ 2.90388121e-04  9.99995229e-01 -3.07545358e-

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004274.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.746179, and correspondence_set size of 42191
Access transformation to get result.
Transformation is:
[[ 9.99994195e-01  1.37500241e-04 -3.40453509e-03 -2.71856583e+01]
 [-1.38324690e-04  9.99999961e-01 -2.41927684e-04  2.20114025e-01]
 [ 3.40450169e-03  2.42397211e-04  9.99994175e-01 -2.71238514e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4          5
0  0.073491 -0.497212 -1.615908 -3430.404587  3956.197341 -83.931235

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004275.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.630114, and correspondence_set size of 42383
Access transformation to get result.
Transformation is:
[[ 9.99994005e-01  1.26558003e-04 -3.46021568e-03 -2.62703311e+01]
 [-1.27076775e-04  9.99999981e-01 -1.497051

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004287.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 17.228172, and correspondence_set size of 40174
Access transformation to get result.
Transformation is:
[[ 9.99999995e-01  8.39667892e-05 -5.54968892e-05 -3.22327128e+01]
 [-8.40175268e-05  9.99999578e-01 -9.14873093e-04  1.18958308e+00]
 [ 5.54200468e-05  9.14877751e-04  9.99999580e-01  6.44629621e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2            3            4           5
0  0.082622 -0.521663 -1.62044 -3794.843973  4000.774945 -145.092053

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004288.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.831537, and correspondence_set size of 39730
Access transformation to get result.
Transformation is:
[[ 9.99999926e-01  2.56972145e-04 -2.86387010e-04 -3.10131186e+01]
 [-2.57535335

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004300.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 17.486634, and correspondence_set size of 39084
Access transformation to get result.
Transformation is:
[[ 9.99998282e-01  9.80598671e-04 -1.57325409e-03 -3.35992127e+01]
 [-9.77378006e-04  9.99997428e-01  2.04660001e-03  3.32294930e+00]
 [ 1.57525694e-03 -2.04505883e-03  9.99996668e-01 -3.98578381e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         0         1         2            3            4          5
0  0.03102 -0.537898 -1.677522 -3800.462791  4303.342826 -313.13825

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004301.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.292737, and correspondence_set size of 39169
Access transformation to get result.
Transformation is:
[[ 9.99998500e-01  6.40860673e-04 -1.60928307e-03 -3.44498305e+01]
 [-6.37413699e-04  9.99997504e-01  2.14153215

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004313.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 30.217101, and correspondence_set size of 39344
Access transformation to get result.
Transformation is:
[[ 9.99999959e-01  1.49174353e-04  2.46151531e-04 -3.79301554e+01]
 [-1.49071777e-04  9.99999902e-01 -4.16684427e-04  1.00681185e+00]
 [-2.46213666e-04  4.16647715e-04  9.99999883e-01 -9.13807587e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0  0.019451 -0.545733 -1.696713 -4095.832392  4419.700491 -357.151351

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004314.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.726899, and correspondence_set size of 39134
Access transformation to get result.
Transformation is:
[[ 9.99999158e-01  1.26420206e-03 -2.92385685e-04 -2.19014295e+01]
 [-1.264332

RegistrationResult with fitness = 1.000000, inlier_rmse = 12.700651, and correspondence_set size of 39207
Access transformation to get result.
Transformation is:
[[ 9.99999598e-01  8.72366816e-04 -2.08060158e-04 -2.29530440e+01]
 [-8.72447021e-04  9.99999545e-01 -3.85706897e-04  5.85443505e+00]
 [ 2.07723585e-04  3.85888263e-04  9.99999904e-01 -4.73645890e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3           4           5
0  0.014298 -0.55336 -1.703688 -4440.195481  4480.17574 -411.419609

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004327.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 20.626074, and correspondence_set size of 39330
Access transformation to get result.
Transformation is:
[[ 9.99997223e-01  2.31193144e-03 -4.56053366e-04 -1.42806172e+01]
 [-2.31215718e-03  9.99997204e-01 -4.95079589e-04  1.18243698e+01]
 [ 4.54907501e-04  4.96132682e-04  9.99999

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004339.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.552210, and correspondence_set size of 41152
Access transformation to get result.
Transformation is:
[[ 9.99999504e-01  9.17629620e-04 -3.86281965e-04 -3.04776601e+01]
 [-9.17909254e-04  9.99999316e-01 -7.24357449e-04  4.78299097e+00]
 [ 3.85617009e-04  7.24711662e-04  9.99999663e-01 -1.13661718e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2           3            4          5
0  0.004517 -0.559207 -1.72547 -4705.25902  4676.608595 -437.61566

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004340.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.049110, and correspondence_set size of 41345
Access transformation to get result.
Transformation is:
[[ 9.99999586e-01  7.60013816e-04 -4.99696627e-04 -2.92950784e+01]
 [-7.60142952e-04

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004352.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.860603, and correspondence_set size of 43066
Access transformation to get result.
Transformation is:
[[ 9.99999567e-01  4.00734725e-04 -8.39377595e-04 -3.35325514e+01]
 [-4.00802715e-04  9.99999916e-01 -8.08344566e-05  3.24096692e+00]
 [ 8.39345131e-04  8.11708464e-05  9.99999644e-01 -4.41810197e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4          5
0 -0.006988 -0.570848 -1.749412 -4870.592204  4899.866102 -504.31524

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004353.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.813038, and correspondence_set size of 43233
Access transformation to get result.
Transformation is:
[[ 9.99999880e-01  2.89444643e-04 -3.96461138e-04 -3.47796329e+01]
 [-2.89557417e-04  9.99999918e-01 -2.844241

Access transformation to get result.
Transformation is:
[[ 9.99999871e-01  6.39396145e-05 -5.04231968e-04 -1.59511102e+01]
 [-6.40110294e-05  9.99999988e-01 -1.41616236e-04  3.93256497e+00]
 [ 5.04222907e-04  1.41648494e-04  9.99999863e-01 -1.40889041e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.011179 -0.579825 -1.757405 -5098.500691  4984.341741 -561.789078

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004366.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 23.467862, and correspondence_set size of 43756
Access transformation to get result.
Transformation is:
[[ 9.99999726e-01 -4.40069486e-04  5.94744928e-04 -1.81995103e+01]
 [ 4.44685669e-04  9.99969606e-01 -7.78390334e-03  1.97623112e+00]
 [-5.91301394e-04  7.78416568e-03  9.99969528e-01 -1.36587372e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004378.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 35.127242, and correspondence_set size of 43842
Access transformation to get result.
Transformation is:
[[ 9.99992300e-01  1.75255841e-03 -3.51123534e-03 -1.16163155e+01]
 [-1.76470222e-03  9.99992462e-01 -3.45845104e-03  1.06513469e+01]
 [ 3.50514773e-03  3.46462070e-03  9.99987855e-01 -8.33708618e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.002558 -0.587849 -1.767686 -5415.041784  5089.943181 -543.809049

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004379.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 26.361411, and correspondence_set size of 43948
Access transformation to get result.
Transformation is:
[[ 9.99995546e-01  2.72272675e-03 -1.22275124e-03  1.13121622e+00]
 [-2.72296690e-03  9.99996274e-01 -1.9477

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004391.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.574587, and correspondence_set size of 44285
Access transformation to get result.
Transformation is:
[[ 9.99999744e-01  6.32927653e-04 -3.34433643e-04 -2.83513581e+01]
 [-6.33061882e-04  9.99999719e-01 -4.01408626e-04  3.26528538e+00]
 [ 3.34179487e-04  4.01620240e-04  9.99999864e-01 -3.20307364e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.011014 -0.597342 -1.786618 -5589.194323  5265.130457 -597.610365

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004392.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.395563, and correspondence_set size of 44359
Access transformation to get result.
Transformation is:
[[ 9.99999714e-01  7.10409222e-04 -2.61174076e-04 -2.66738719e+01]
 [-7.105837

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004404.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.146794, and correspondence_set size of 42870
Access transformation to get result.
Transformation is:
[[ 9.99999691e-01  4.18672949e-04 -6.65454879e-04 -3.44459142e+01]
 [-4.18965788e-04  9.99999815e-01 -4.39980159e-04  3.20154354e+00]
 [ 6.65270549e-04  4.40258826e-04  9.99999682e-01 -6.20843444e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4          5
0 -0.015187 -0.605696 -1.806244 -5750.174175  5439.044757 -622.97754

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004405.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.994432, and correspondence_set size of 42808
Access transformation to get result.
Transformation is:
[[ 9.99999137e-01  1.23370342e-03 -4.50858487e-04 -3.18959561e+01]
 [-1.23373687

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004417.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.879382, and correspondence_set size of 43062
Access transformation to get result.
Transformation is:
[[ 9.99996496e-01  2.64700242e-03 -2.06648800e-05 -2.15169121e+01]
 [-2.64700501e-03  9.99996489e-01 -1.26318615e-04  8.47422227e+00]
 [ 2.03304417e-05  1.26372872e-04  9.99999992e-01 -1.34878473e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.039369 -0.617573 -1.841006 -5816.795094  5710.727553 -745.849289

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004418.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.543915, and correspondence_set size of 43159
Access transformation to get result.
Transformation is:
[[ 9.99999756e-01  4.83243642e-04 -5.03503033e-04 -3.00324042e+01]
 [-4.833899

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004430.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 27.720594, and correspondence_set size of 43700
Access transformation to get result.
Transformation is:
[[ 9.99996486e-01  2.29714827e-03 -1.32353603e-03  4.05728312e-01]
 [-2.29769258e-03  9.99997276e-01 -4.09876223e-04  8.97487111e+00]
 [ 1.32259088e-03  4.12915862e-04  9.99999040e-01 -2.59244935e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.042668 -0.623361 -1.859296 -6056.118087  5852.810322 -746.182278

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004431.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 30.585457, and correspondence_set size of 43551
Access transformation to get result.
Transformation is:
[[ 9.99991681e-01  3.96606933e-03 -9.52657999e-04  4.49509316e+00]
 [-3.966194

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004443.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.490502, and correspondence_set size of 42529
Access transformation to get result.
Transformation is:
[[ 9.99998845e-01  1.50571355e-03 -2.06560604e-04 -2.63472855e+01]
 [-1.50583429e-03  9.99998695e-01 -5.85635261e-04  4.57734454e+00]
 [ 2.05678536e-04  5.85945630e-04  9.99999807e-01  1.26945655e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2            3           4           5
0 -0.053124 -0.629792 -1.89057 -6185.114349  6087.59954 -754.783443

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004444.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.185116, and correspondence_set size of 42625
Access transformation to get result.
Transformation is:
[[ 9.99998068e-01  1.91163814e-03 -4.56929220e-04 -2.43254768e+01]
 [-1.91182677e-03  9.99998087e-01 -4.12758605

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004456.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.116600, and correspondence_set size of 42450
Access transformation to get result.
Transformation is:
[[ 9.99998025e-01  1.96826222e-03  2.77243636e-04 -3.24893158e+01]
 [-1.96886789e-03  9.99995638e-01  2.20152848e-03  2.61372838e+00]
 [-2.72909242e-04 -2.20206999e-03  9.99997538e-01  7.62945396e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.070216 -0.637994 -1.924641 -6232.721453  6319.962353 -810.881077

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004457.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.485410, and correspondence_set size of 42447
Access transformation to get result.
Transformation is:
[[ 9.99999426e-01  9.88217892e-04 -4.14498227e-04 -3.12939256e+01]
 [-9.883202

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004469.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.147831, and correspondence_set size of 41862
Access transformation to get result.
Transformation is:
[[ 9.99999434e-01  1.05680327e-03 -1.20387820e-04 -1.77285732e+01]
 [-1.05679853e-03  9.99999441e-01  3.94597516e-05  3.75562739e+00]
 [ 1.20429453e-04 -3.93325036e-05  9.99999992e-01 -2.13998559e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.082963 -0.655652 -1.947418 -6376.047741  6466.318938 -937.924716

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004470.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 34.683930, and correspondence_set size of 41699
Access transformation to get result.
Transformation is:
[[ 9.99964798e-01  4.72725941e-03 -6.93216103e-03  3.04208672e+00]
 [-4.744818

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004482.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 23.700656, and correspondence_set size of 41240
Access transformation to get result.
Transformation is:
[[ 9.99992640e-01 -2.44228575e-03  2.95886144e-03 -9.30314952e+00]
 [ 2.44790199e-03  9.99995207e-01 -1.89597585e-03 -5.55264922e+00]
 [-2.95421674e-03  1.90320490e-03  9.99993825e-01 -1.17511890e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.092652 -0.669693 -1.970054 -6244.890066  6616.262953 -1024.861544

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004483.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.084016, and correspondence_set size of 41044
Access transformation to get result.
Transformation is:
[[ 9.99993412e-01  3.62978678e-03  3.94889219e-06  1.40838147e+01]
 [-3.62978893e-03  9.99992861e-01  1.05

Access transformation to get result.
Transformation is:
[[ 9.99999965e-01  2.45378882e-04  9.89775132e-05  9.04239143e-01]
 [-2.45385782e-04  9.99999967e-01  6.97112113e-05  2.77812631e-01]
 [-9.89604043e-05 -6.97354965e-05  9.99999993e-01 -6.49878624e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.106569 -0.670725 -1.989332 -6075.595667  6741.777064 -1064.087916

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004495.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 4.768357, and correspondence_set size of 40282
Access transformation to get result.
Transformation is:
[[ 9.99999970e-01  2.28104346e-04 -8.98468346e-05  7.43402162e-01]
 [-2.28100598e-04  9.99999973e-01  4.17271980e-05  2.42084937e-01]
 [ 8.98563504e-05 -4.17067027e-05  9.99999995e-01 -1.71017861e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
        

RegistrationResult with fitness = 1.000000, inlier_rmse = 10.897337, and correspondence_set size of 40074
Access transformation to get result.
Transformation is:
[[ 9.99999832e-01 -5.78917700e-04  8.95720201e-06 -1.81413454e-01]
 [ 5.78917866e-04  9.99999832e-01 -1.85514360e-05 -7.00758132e-01]
 [-8.94646075e-06  1.85566184e-05  1.00000000e+00  8.55951893e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.104939 -0.668598 -1.989466 -6072.995049  6744.667157 -1038.358521

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004508.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 8.303249, and correspondence_set size of 40033
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01  4.26202140e-05  5.85984423e-06 -8.25268187e-02]
 [-4.26202356e-05  9.99999999e-01  3.67408212e-06 -8.76407335e-02]
 [-5.85968763e-06 -3.67433187e-06  1.

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004520.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 4.130897, and correspondence_set size of 40013
Access transformation to get result.
Transformation is:
[[ 9.99999996e-01  8.48782779e-05  3.17349325e-05 -5.67147886e-02]
 [-8.48782457e-05  9.99999996e-01 -1.01834544e-06 -9.06117027e-02]
 [-3.17350188e-05  1.01565183e-06  9.99999999e-01  2.48605081e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.105329 -0.668908 -1.989783 -6072.288235  6743.886861 -1042.099944

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004521.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.932968, and correspondence_set size of 39986
Access transformation to get result.
Transformation is:
[[ 9.99999997e-01  6.39824122e-05 -3.90482286e-05 -7.04551685e-02]
 [-6.398263

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004533.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.896962, and correspondence_set size of 40009
Access transformation to get result.
Transformation is:
[[ 1.00000000e+00  8.39449220e-06 -2.06259179e-05 -1.38244991e-01]
 [-8.39486067e-06  1.00000000e+00 -1.78642381e-05 -5.17518519e-02]
 [ 2.06257680e-05  1.78644112e-05  1.00000000e+00 -4.56169178e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3            4            5
0 -0.106281 -0.66941 -1.990521 -6069.296487  6744.946997 -1049.469369

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004534.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.483109, and correspondence_set size of 40031
Access transformation to get result.
Transformation is:
[[ 9.99999998e-01 -2.80745111e-05 -5.63054470e-05 -9.85962427e-02]
 [ 2.80728954

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004546.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.230137, and correspondence_set size of 39997
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01 -2.74596431e-05 -3.11741954e-05 -2.10384659e-02]
 [ 2.74595412e-05  1.00000000e+00 -3.27154272e-06 -5.98199846e-02]
 [ 3.11742852e-05  3.27068669e-06  1.00000000e+00 -3.08251602e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2          3           4            5
0 -0.105961 -0.669619 -1.990122 -6072.1863  6741.93923 -1050.262028

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004547.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.493758, and correspondence_set size of 40005
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01  3.64953959e-05 -1.14231740e-05 -3.54860127e-02]
 [-3.64956604e-05

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004559.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.702452, and correspondence_set size of 40022
Access transformation to get result.
Transformation is:
[[ 1.00000000e+00 -7.50276972e-06 -2.12974747e-05 -5.35215303e-02]
 [ 7.50287143e-06  1.00000000e+00  4.77566878e-06 -3.12586085e-02]
 [ 2.12974388e-05 -4.77582857e-06  1.00000000e+00 -1.61255954e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.105713 -0.669927 -1.989954 -6073.745831  6740.654123 -1051.359753

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004560.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.662244, and correspondence_set size of 40023
Access transformation to get result.
Transformation is:
[[ 1.00000000e+00 -2.33403721e-05 -5.65744829e-07 -4.81909197e-02]
 [ 2.33403644e-05  1.00000000e+00 -1.3494

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004572.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.624391, and correspondence_set size of 40016
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01  3.61708377e-06 -3.19338636e-05 -5.80563946e-02]
 [-3.61711859e-06  1.00000000e+00 -1.09046893e-06  4.26584022e-03]
 [ 3.19338597e-05  1.09058444e-06  9.99999999e-01 -3.73413778e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.105533 -0.670082 -1.989874 -6074.760211  6740.082696 -1051.545302

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004573.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.694958, and correspondence_set size of 40009
Access transformation to get result.
Transformation is:
[[ 1.00000000e+00 -2.40110705e-05  9.95555398e-06 -7.47629843e-02]
 [ 2.40111287e-05  1.00000000e+00 -5.8502

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004585.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.947522, and correspondence_set size of 40000
Access transformation to get result.
Transformation is:
[[ 1.00000000e+00  4.07574643e-06 -1.90545319e-05 -6.98417796e-02]
 [-4.07616549e-06  1.00000000e+00 -2.19929566e-05  8.33937759e-04]
 [ 1.90544422e-05  2.19930343e-05  1.00000000e+00 -1.51679878e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.105194 -0.670339 -1.989747 -6076.158388  6739.350649 -1051.545031

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004586.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 4.451760, and correspondence_set size of 39992
Access transformation to get result.
Transformation is:
[[ 9.99999972e-01  9.85194856e-05 -2.14207618e-04 -6.83049343e-02]
 [-9.852470

RegistrationResult with fitness = 1.000000, inlier_rmse = 2.977536, and correspondence_set size of 40033
Access transformation to get result.
Transformation is:
[[ 9.99999998e-01 -2.01871069e-05 -5.32597300e-05 -8.26312814e-02]
 [ 2.01848894e-05  9.99999999e-01 -4.16362679e-05 -4.13533043e-02]
 [ 5.32605705e-05  4.16351927e-05  9.99999998e-01 -5.19645117e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3            4            5
0 -0.104947 -0.67101 -1.989854 -6076.350877  6739.651037 -1054.147176

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004599.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.070224, and correspondence_set size of 40039
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01 -2.56199450e-05 -2.09489378e-05 -7.58245173e-02]
 [ 2.56193122e-05  9.99999999e-01 -3.02097240e-05 -6.51520178e-02]
 [ 2.09497118e-05  3.02091873e-05  9.999

E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004611.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 2.875807, and correspondence_set size of 40007
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01  6.74855039e-06 -4.92311604e-05 -6.83032065e-02]
 [-6.75150125e-06  9.99999998e-01 -5.99389334e-05 -2.04283166e-02]
 [ 4.92307558e-05  5.99392657e-05  9.99999997e-01 -3.07590918e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3            4            5
0 -0.104409 -0.67148 -1.989627 -6078.461829  6738.262534 -1054.480433

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004612.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.202942, and correspondence_set size of 39978
Access transformation to get result.
Transformation is:
[[ 9.99999998e-01 -3.17994564e-05 -5.99108902e-05 -9.06884843e-02]
 [ 3.17972235e-05  9.99999999e-01 -3.727184

RegistrationResult with fitness = 1.000000, inlier_rmse = 2.902921, and correspondence_set size of 40031
Access transformation to get result.
Transformation is:
[[ 9.99999998e-01 -4.02820215e-05 -4.63466142e-05 -1.12603672e-01]
 [ 4.02794823e-05  9.99999998e-01 -5.47865735e-05 -4.99677859e-02]
 [ 4.63488210e-05  5.47847066e-05  9.99999997e-01 -1.93947046e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.103689 -0.672076 -1.989278 -6081.464663  6736.285946 -1054.848895

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004625.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.351355, and correspondence_set size of 40033
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01 -2.41197072e-05 -3.07004433e-05 -1.12558875e-01]
 [ 2.41180279e-05  9.99999998e-01 -5.46973646e-05 -3.66895958e-02]
 [ 3.07017625e-05  5.46966241e-05  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 3.535536, and correspondence_set size of 40013
Access transformation to get result.
Transformation is:
[[ 9.99999997e-01 -5.32097999e-05 -4.93143963e-05 -1.44567084e-01]
 [ 5.32072185e-05  9.99999997e-01 -5.23464273e-05 -6.79943483e-02]
 [ 4.93171815e-05  5.23438033e-05  9.99999997e-01 -1.50930718e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.102776 -0.672714 -1.988862 -6085.024543  6734.019168 -1054.368045

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004638.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 6.066987, and correspondence_set size of 40007
Access transformation to get result.
Transformation is:
[[ 9.99999999e-01  3.22177901e-05  9.90590640e-06 -1.30678472e-01]
 [-3.22173473e-05  9.99999998e-01 -4.47039908e-05  1.54846789e-02]
 [-9.90734665e-06  4.47036717e-05  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 3.942245, and correspondence_set size of 40030
Access transformation to get result.
Transformation is:
[[ 9.99999995e-01 -7.15134127e-05 -6.43850310e-05 -1.91286658e-01]
 [ 7.15085741e-05  9.99999995e-01 -7.51507025e-05 -9.75416670e-02]
 [ 6.43904049e-05  7.51460981e-05  9.99999995e-01 -7.90309704e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.101419 -0.673408 -1.988297 -6089.759375  6731.166953 -1051.601566

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004651.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 3.580176, and correspondence_set size of 40034
Access transformation to get result.
Transformation is:
[[ 9.99999996e-01 -5.43763642e-05 -7.29978123e-05 -1.92880276e-01]
 [ 5.43698773e-05  9.99999995e-01 -8.88625035e-05 -8.55173158e-02]
 [ 7.30026439e-05  8.88585343e-05  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 28.009446, and correspondence_set size of 38814
Access transformation to get result.
Transformation is:
[[ 9.99995619e-01 -2.88156759e-03  6.76686753e-04 -1.91341937e+01]
 [ 2.88168899e-03  9.99995832e-01 -1.78498979e-04 -5.16857341e+00]
 [-6.76169576e-04  1.80448197e-04  9.99999755e-01 -8.97515392e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.099295 -0.664603 -1.983271 -6162.683973  6708.913584 -1006.74429

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004664.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 26.126267, and correspondence_set size of 38423
Access transformation to get result.
Transformation is:
[[ 9.99985093e-01  5.45086602e-03 -3.19040164e-04  6.23698676e+00]
 [-5.45054412e-03  9.99984644e-01  1.00127547e-03  1.07401840e+01]
 [ 3.24493083e-04 -9.99521602e-04  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 15.332266, and correspondence_set size of 36994
Access transformation to get result.
Transformation is:
[[ 9.99999952e-01  2.25673327e-05 -3.08559517e-04 -3.08765222e+01]
 [-2.29047920e-05  9.99999402e-01 -1.09370059e-03  2.41499006e+00]
 [ 3.08534650e-04  1.09370761e-03  9.99999354e-01  1.03866733e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.119383 -0.666909 -2.018687 -6143.336106  6953.597681 -1030.089043

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004677.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 22.587888, and correspondence_set size of 37165
Access transformation to get result.
Transformation is:
[[ 9.99999053e-01 -1.37479843e-03 -6.84117681e-05 -3.73708260e+01]
 [ 1.37469161e-03  9.99997873e-01 -1.53772691e-03 -1.67503422e+00]
 [ 7.05256871e-05  1.53763141e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 18.531183, and correspondence_set size of 39675
Access transformation to get result.
Transformation is:
[[ 9.99996896e-01  2.12091290e-03 -1.30778128e-03 -3.33749926e+01]
 [-2.11850877e-03  9.99996069e-01  1.83697965e-03  5.12461416e+00]
 [ 1.31167221e-03 -1.83420341e-03  9.99997458e-01 -2.75112470e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3           4            5
0 -0.178392 -0.700433 -2.072235 -6301.799384  7177.14562 -1459.597934

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004690.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.401457, and correspondence_set size of 39892
Access transformation to get result.
Transformation is:
[[ 9.99999300e-01  1.17611187e-03 -1.28843577e-04 -3.26865645e+01]
 [-1.17616536e-03  9.99999222e-01 -4.15850435e-04  3.29315453e+00]
 [ 1.28354390e-04  4.16001685e-04  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 13.434105, and correspondence_set size of 41167
Access transformation to get result.
Transformation is:
[[ 9.99998426e-01  1.73058913e-03 -3.92423736e-04 -2.91695232e+01]
 [-1.73067534e-03  9.99998478e-01 -2.19462083e-04  2.97125281e+00]
 [ 3.92043340e-04  2.20140896e-04  9.99999899e-01  1.08465584e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.161774 -0.704058 -2.065675 -6758.141588  7156.637891 -1395.621508

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004703.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 19.555851, and correspondence_set size of 40910
Access transformation to get result.
Transformation is:
[[ 9.99998621e-01  1.35353608e-03 -9.62684012e-04 -3.56247838e+01]
 [-1.35134004e-03  9.99996492e-01  2.27816763e-03  2.29659632e+00]
 [ 9.65764217e-04 -2.27686357e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 31.525189, and correspondence_set size of 44993
Access transformation to get result.
Transformation is:
[[ 9.99972432e-01 -1.59571037e-03 -7.25185338e-03 -2.67040014e+01]
 [ 1.60152730e-03  9.99998400e-01  7.96394626e-04 -1.59652142e-01]
 [ 7.25057097e-03 -8.07986712e-04  9.99973388e-01 -1.11235018e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.196315 -0.744586 -2.094807 -6982.240908  7276.872007 -1827.552325

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004716.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 26.984043, and correspondence_set size of 45512
Access transformation to get result.
Transformation is:
[[ 9.99998930e-01 -7.14347165e-04  1.27671062e-03 -2.67319989e+01]
 [ 7.12350342e-04  9.99998524e-01  1.56380811e-03 -1.17420773e+00]
 [-1.27782584e-03 -1.56289697e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 9.455055, and correspondence_set size of 44844
Access transformation to get result.
Transformation is:
[[ 9.99989851e-01  1.07820257e-03 -4.37435552e-03 -7.27039758e+00]
 [-1.07874435e-03  9.99999411e-01 -1.21494269e-04  2.79394393e+00]
 [ 4.37422195e-03  1.26211847e-04  9.99990425e-01 -4.57652317e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4          5
0 -0.231276 -0.745183 -2.137058 -6897.916966  7563.379154 -1944.3231

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004729.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 33.882627, and correspondence_set size of 45218
Access transformation to get result.
Transformation is:
[[ 9.99979989e-01  1.31574924e-03 -6.18786965e-03  5.50778091e+00]
 [-1.30973062e-03  9.99998665e-01  9.76600834e-04  1.03532540e+01]
 [ 6.18914636e-03 -9.68476849e-04  9.9998

RegistrationResult with fitness = 1.000000, inlier_rmse = 23.241021, and correspondence_set size of 43313
Access transformation to get result.
Transformation is:
[[ 9.99992351e-01 -8.65605128e-04  3.81433013e-03 -1.77478191e+01]
 [ 8.66796289e-04  9.99999576e-01 -3.10643610e-04 -2.39907163e+00]
 [-3.81405962e-03  3.13947481e-04  9.99992677e-01  5.54445971e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2            3            4            5
0 -0.252756 -0.728156 -2.15496 -6779.687801  7742.180226 -1948.220531

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004742.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 29.182731, and correspondence_set size of 43010
Access transformation to get result.
Transformation is:
[[ 9.99999074e-01 -1.17322057e-03  6.88988429e-04 -2.18446878e+01]
 [ 1.17230407e-03  9.99998430e-01  1.32911863e-03 -8.19656216e-01]
 [-6.90546696e-04 -1.32830970e-03  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 13.603291, and correspondence_set size of 41638
Access transformation to get result.
Transformation is:
[[ 9.99996532e-01  2.57108480e-03 -5.69700586e-04 -2.84020489e+01]
 [-2.57100087e-03  9.99996684e-01  1.47996622e-04  8.40602427e+00]
 [ 5.70079209e-04 -1.46531408e-04  9.99999827e-01  2.19956644e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.288289 -0.725598 -2.202531 -6626.944307  8111.245757 -2042.770992

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004755.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 22.270474, and correspondence_set size of 41934
Access transformation to get result.
Transformation is:
[[ 9.99998932e-01  6.00665219e-04 -1.33255539e-03 -3.67147739e+01]
 [-6.00358745e-04  9.99999793e-01  2.30378214e-04  1.95352943e+00]
 [ 1.33269350e-03 -2.29577957e-04  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 16.165806, and correspondence_set size of 45835
Access transformation to get result.
Transformation is:
[[ 9.99999476e-01  9.52905171e-04 -3.73937535e-04 -3.45266050e+01]
 [-9.52951310e-04  9.99999538e-01 -1.23227299e-04  3.42066216e+00]
 [ 3.73819938e-04  1.23583579e-04  9.99999922e-01  8.78479980e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2            3            4            5
0 -0.315025 -0.758433 -2.22018 -7042.194017  8119.348559 -2408.498598

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004768.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.109227, and correspondence_set size of 45915
Access transformation to get result.
Transformation is:
[[ 9.99999166e-01  1.23390642e-03 -3.80219058e-04 -3.23058736e+01]
 [-1.23394018e-03  9.99999235e-01 -8.85606759e-05  3.67814569e+00]
 [ 3.80109491e-04  8.90297697e-05  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 35.758732, and correspondence_set size of 45465
Access transformation to get result.
Transformation is:
[[ 9.99999922e-01  3.27970092e-04  2.20846596e-04 -3.56721949e+01]
 [-3.28327740e-04  9.99998632e-01  1.62135565e-03  3.09586991e+00]
 [-2.20314538e-04 -1.62142804e-03  9.99998661e-01 -2.16160790e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.339365 -0.756418 -2.249336 -7179.264295  8319.112793 -2492.639542

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004781.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 38.980306, and correspondence_set size of 45161
Access transformation to get result.
Transformation is:
[[ 9.99998165e-01 -4.10405298e-04 -1.87124086e-03  5.91054456e+00]
 [ 4.13598301e-04  9.99998459e-01  1.70628832e-03  8.05412122e+00]
 [ 1.87053771e-03 -1.70705913e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 15.246857, and correspondence_set size of 46128
Access transformation to get result.
Transformation is:
[[ 9.99999271e-01  1.15327938e-03 -3.58125817e-04 -2.91248886e+01]
 [-1.15323101e-03  9.99999326e-01  1.35231894e-04  3.81743332e+00]
 [ 3.58281536e-04 -1.34818794e-04  9.99999927e-01 -5.48706417e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.347789 -0.761939 -2.259923 -7493.603086  8399.067992 -2563.294612

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004794.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 12.460753, and correspondence_set size of 46216
Access transformation to get result.
Transformation is:
[[ 9.99999839e-01  4.99988859e-04 -2.70057231e-04 -2.85963557e+01]
 [-5.00142397e-04  9.99999713e-01 -5.68769503e-04  3.34672387e+00]
 [ 2.69772775e-04  5.68904478e-04  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 16.403824, and correspondence_set size of 44710
Access transformation to get result.
Transformation is:
[[ 9.99999939e-01  2.05187089e-04 -2.83871217e-04 -3.41063767e+01]
 [-2.05217814e-04  9.99999973e-01 -1.08210601e-04  1.12663772e+00]
 [ 2.83849006e-04  1.08268850e-04  9.99999954e-01  2.55444083e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1       2            3            4            5
0 -0.369316 -0.758668 -2.2873 -7526.080971  8644.618379 -2627.346729

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004807.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 18.245975, and correspondence_set size of 44601
Access transformation to get result.
Transformation is:
[[ 9.99999545e-01  2.87691248e-04 -9.09171504e-04 -3.28429739e+01]
 [-2.87410496e-04  9.99999911e-01  3.08914935e-04  3.79722994e+00]
 [ 9.09260295e-04 -3.08653489e-04  9.999

RegistrationResult with fitness = 1.000000, inlier_rmse = 35.241608, and correspondence_set size of 44641
Access transformation to get result.
Transformation is:
[[ 9.99996681e-01  2.52877627e-03 -4.93408297e-04  3.62956600e+00]
 [-2.52833643e-03  9.99996408e-01  8.90038065e-04  2.01319450e+01]
 [ 4.95657231e-04 -8.88787608e-04  9.99999482e-01 -2.19322175e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.390789 -0.763207 -2.308069 -7668.564961  8806.754774 -2782.384725

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004820.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 26.710349, and correspondence_set size of 44535
Access transformation to get result.
Transformation is:
[[ 9.99999154e-01  1.12167010e-03 -6.59059700e-04 -8.42225871e-01]
 [-1.12153685e-03  9.99999351e-01  2.02523072e-04  1.58963959e+01]
 [ 6.59286436e-04 -2.01783741e-04  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 12.505381, and correspondence_set size of 44797
Access transformation to get result.
Transformation is:
[[ 9.99999744e-01  6.12733692e-04 -3.68272369e-04 -2.50989951e+01]
 [-6.12893396e-04  9.99999718e-01 -4.33701454e-04  4.22020067e+00]
 [ 3.68006522e-04  4.33927055e-04  9.99999838e-01 -6.89182275e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2           3            4            5
0 -0.390942 -0.767243 -2.311933 -8004.32724  8862.463655 -2800.776212

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004833.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 28.304961, and correspondence_set size of 44738
Access transformation to get result.
Transformation is:
[[ 9.99999679e-01  7.11561227e-04 -3.67383241e-04 -8.78226056e+00]
 [-7.11741054e-04  9.99999627e-01 -4.89580748e-04  6.96519233e+00]
 [ 3.67034738e-04  4.89842073e-04  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 14.050437, and correspondence_set size of 44131
Access transformation to get result.
Transformation is:
[[ 9.99998532e-01  1.17012294e-03 -1.25139819e-03 -2.92250836e+01]
 [-1.17356648e-03  9.99995518e-01 -2.75457411e-03  4.40553362e+00]
 [ 1.24816940e-03  2.75603867e-03  9.99995423e-01 -9.29683649e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1         2            3            4            5
0 -0.390067 -0.77108 -2.319703 -8197.955774  8965.026554 -2799.475283

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004846.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.376246, and correspondence_set size of 44428
Access transformation to get result.
Transformation is:
[[ 9.99998256e-01  1.07965875e-03 -1.52384076e-03 -2.91180816e+01]
 [-1.08339509e-03  9.99996404e-01 -2.45323075e-03  3.51847472e+00]
 [ 1.52118663e-03  2.45487740e-03  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 16.076445, and correspondence_set size of 45208
Access transformation to get result.
Transformation is:
[[ 9.99998706e-01 -8.80155284e-04 -1.34658432e-03 -3.33940712e+01]
 [ 8.77146137e-04  9.99997121e-01 -2.23361287e-03 -1.01451287e-01]
 [ 1.34854637e-03  2.23242883e-03  9.99996599e-01 -7.62638492e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0        1       2            3            4            5
0 -0.356363 -0.79584 -2.3197 -8437.165762  9025.589139 -2716.865479

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004859.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 16.613423, and correspondence_set size of 45361
Access transformation to get result.
Transformation is:
[[ 9.99999107e-01 -4.05348097e-04 -1.27328149e-03 -3.10393793e+01]
 [ 4.01328554e-04  9.99994941e-01 -3.15550855e-03  9.57840487e-01]
 [ 1.27455413e-03  3.15499473e-03  9.99994

RegistrationResult with fitness = 1.000000, inlier_rmse = 40.913645, and correspondence_set size of 45654
Access transformation to get result.
Transformation is:
[[ 9.99979097e-01 -2.99401686e-03 -5.73082652e-03  1.42207787e-01]
 [ 2.98418031e-03  9.99994061e-01 -1.72420939e-03 -4.12804855e+00]
 [ 5.73595480e-03  1.70707153e-03  9.99982092e-01 -1.94071458e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         0         1         2            3            4            5
0 -0.30705 -0.828021 -2.299134 -8788.185213  8885.804306 -2676.260402

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004872.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 14.479306, and correspondence_set size of 45461
Access transformation to get result.
Transformation is:
[[ 9.99996958e-01 -1.84146612e-03 -1.64080510e-03 -1.63083915e+01]
 [ 1.83686486e-03  9.99994389e-01 -2.80137862e-03 -2.90084678e+00]
 [ 1.64595454e-03  2.79835616e-03  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 15.662964, and correspondence_set size of 44474
Access transformation to get result.
Transformation is:
[[ 9.99996006e-01 -2.02153651e-03 -1.97493840e-03 -9.92321927e+00]
 [ 2.01656353e-03  9.99994800e-01 -2.51679714e-03 -1.85213994e+00]
 [ 1.98001593e-03  2.51280450e-03  9.99994883e-01 -2.34119966e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4           5
0 -0.263161 -0.852311 -2.288585 -9185.853799  8861.717266 -2565.77175

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004885.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 25.093016, and correspondence_set size of 44489
Access transformation to get result.
Transformation is:
[[ 9.99991593e-01 -3.27981134e-03 -2.46093674e-03  2.25326082e+00]
 [ 3.27423660e-03  9.99992072e-01 -2.26591487e-03 -4.62889543e+00]
 [ 2.46834900e-03  2.25783813e-03  9.9

RegistrationResult with fitness = 1.000000, inlier_rmse = 13.760279, and correspondence_set size of 45201
Access transformation to get result.
Transformation is:
[[ 9.99998256e-01 -6.87661638e-04 -1.73624583e-03 -2.78828216e+01]
 [ 6.83197111e-04  9.99996462e-01 -2.57065357e-03  1.00680703e+00]
 [ 1.73800743e-03  2.56946289e-03  9.99995189e-01 -1.47594589e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.215628 -0.880554 -2.269645 -9540.157371  8768.173383 -2528.391036

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004898.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.097770, and correspondence_set size of 45403
Access transformation to get result.
Transformation is:
[[ 9.99998692e-01 -7.02329115e-04 -1.45701602e-03 -2.68734379e+01]
 [ 6.98221572e-04  9.99995786e-01 -2.81774276e-03  1.37768351e+00]
 [ 1.45898886e-03  2.81672176e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 16.139002, and correspondence_set size of 45193
Access transformation to get result.
Transformation is:
[[ 9.99998390e-01 -2.92795133e-04 -1.77045308e-03 -3.22203420e+01]
 [ 2.88434636e-04  9.99996926e-01 -2.46268111e-03  1.93351458e+00]
 [ 1.77116870e-03  2.46216648e-03  9.99995400e-01 -1.20558500e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.172861 -0.905166 -2.252316 -9862.923102  8677.862897 -2519.716058

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004911.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.618674, and correspondence_set size of 44992
Access transformation to get result.
Transformation is:
[[ 9.99998954e-01 -2.19683663e-04 -1.42933375e-03 -3.21827181e+01]
 [ 2.15545261e-04  9.99995787e-01 -2.89484614e-03  3.59103602e+00]
 [ 1.42996368e-03  2.89453503e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 14.457719, and correspondence_set size of 42613
Access transformation to get result.
Transformation is:
[[ 9.99997285e-01 -1.47644591e-03 -1.80291155e-03 -2.00352260e+01]
 [ 1.47190925e-03  9.99995754e-01 -2.51503863e-03 -2.56648051e+00]
 [ 1.80661721e-03  2.51237808e-03  9.99995212e-01 -1.92545534e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2            3            4            5
0 -0.113976 -0.934858 -2.219401 -10200.53381  8494.858736 -2541.833372

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004924.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.043683, and correspondence_set size of 42667
Access transformation to get result.
Transformation is:
[[ 9.99998719e-01 -3.85429302e-04 -1.55353744e-03 -3.04304171e+01]
 [ 3.81430464e-04  9.99996616e-01 -2.57349595e-03  5.31211212e-01]
 [ 1.55452408e-03  2.57290009e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 23.259513, and correspondence_set size of 44511
Access transformation to get result.
Transformation is:
[[ 9.99992379e-01 -2.89188407e-03 -2.62286274e-03  1.32825391e+00]
 [ 2.88678568e-03  9.99993941e-01 -1.94553611e-03 -3.67213269e+00]
 [ 2.62847311e-03  1.93794964e-03  9.99994668e-01 -4.25578047e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
         0         1         2             3            4            5
0 -0.07257 -0.956718 -2.208236 -10562.102095  8490.714814 -2505.296548

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004937.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 31.545004, and correspondence_set size of 44666
Access transformation to get result.
Transformation is:
[[ 9.99992151e-01 -2.96107461e-03 -2.63237183e-03  4.45162819e+00]
 [ 2.95624288e-03  9.99993942e-01 -1.83750500e-03 -4.88931478e+00]
 [ 2.63779687e-03  1.82970865e-03  9

RegistrationResult with fitness = 1.000000, inlier_rmse = 13.106361, and correspondence_set size of 42422
Access transformation to get result.
Transformation is:
[[ 9.99998637e-01  3.25300330e-05 -1.65076670e-03 -2.71122673e+01]
 [-3.63374429e-05  9.99997339e-01 -2.30647184e-03  3.00231640e+00]
 [ 1.65068728e-03  2.30652869e-03  9.99995978e-01 -1.42961606e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2             3            4            5
0 -0.035041 -0.979784 -2.197237 -10873.888615  8494.341063 -2530.752648

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004950.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.302170, and correspondence_set size of 41863
Access transformation to get result.
Transformation is:
[[ 9.99999023e-01 -5.49980545e-05 -1.39679495e-03 -2.65829376e+01]
 [ 5.19503254e-05  9.99997618e-01 -2.18188707e-03  2.82860908e+00]
 [ 1.39691163e-03  2.18181237e-03 

RegistrationResult with fitness = 1.000000, inlier_rmse = 12.399425, and correspondence_set size of 41144
Access transformation to get result.
Transformation is:
[[ 9.99999145e-01 -1.19124951e-04 -1.30217727e-03 -3.03654933e+01]
 [ 1.16419039e-04  9.99997834e-01 -2.07786868e-03  1.81368271e+00]
 [ 1.30242197e-03  2.07771531e-03  9.99996993e-01 -7.02372597e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2             3            4            5
0 -0.003106 -1.005757 -2.185394 -11122.540408  8487.183686 -2657.030073

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004963.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.727880, and correspondence_set size of 41265
Access transformation to get result.
Transformation is:
[[ 9.99999085e-01 -1.62650195e-05 -1.35277609e-03 -2.96370692e+01]
 [ 1.34189319e-05  9.99997787e-01 -2.10386918e-03  2.79503488e+00]
 [ 1.35280731e-03  2.10384910e-03 

RegistrationResult with fitness = 1.000000, inlier_rmse = 25.003208, and correspondence_set size of 39834
Access transformation to get result.
Transformation is:
[[ 9.99971805e-01  1.69955725e-03 -7.31446125e-03 -3.89612230e+01]
 [-1.70086114e-03  9.99998539e-01 -1.72045428e-04  4.50827604e+00]
 [ 7.31415816e-03  1.84481460e-04  9.99973234e-01 -5.00340979e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1         2             3            4            5
0  0.016179 -1.033806 -2.186478 -11306.428643  8568.265265 -2829.775034

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004976.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 13.320336, and correspondence_set size of 39339
Access transformation to get result.
Transformation is:
[[ 9.99950647e-01 -2.16885535e-03 -9.69534564e-03 -1.89867190e+01]
 [ 2.15867362e-03  9.99997108e-01 -1.06050853e-03  4.10027848e-01]
 [ 9.69761769e-03  1.03952710e-03 

RegistrationResult with fitness = 1.000000, inlier_rmse = 13.275679, and correspondence_set size of 38224
Access transformation to get result.
Transformation is:
[[ 9.99990829e-01  5.24212145e-04  4.25045990e-03 -8.15767105e+00]
 [-5.24127371e-04  9.99999862e-01 -2.10585178e-05  2.78457796e+00]
 [-4.25047035e-03  1.88305423e-05  9.99990967e-01  7.81789428e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
          0         1        2             3            4            5
0  0.023773 -1.051723 -2.18451 -11227.428967  8598.096487 -2992.348475

Apply point-to-point ICP to: 
E:/Datasets/DataHack/Test/vid_21_estimate_egomotion\0004989.xyz
RegistrationResult with fitness = 1.000000, inlier_rmse = 15.846591, and correspondence_set size of 37905
Access transformation to get result.
Transformation is:
[[ 9.99996828e-01  2.77261064e-04  2.50324299e-03 -1.39999251e+01]
 [-2.71524669e-04  9.99997337e-01 -2.29163475e-03  2.91316694e+00]
 [-2.50387171e-03  2.29094779e-03  9

-----------------------------

In [ ]:

from functools import partial
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pycpd import rigid_registration
import numpy as np
import time

def visualize(iteration, error, X, Y, ax):
    plt.cla()
    ax.scatter(X[:,0],  X[:,1], X[:,2], color='red', label='Target')
    ax.scatter(Y[:,0],  Y[:,1], Y[:,2], color='blue', label='Source')
    ax.text2D(0.87, 0.92, 'Iteration: {:d}\nError: {:06.4f}'.format(iteration, error), horizontalalignment='center', verticalalignment='center', transform=ax.transAxes, fontsize='x-large')
    ax.legend(loc='upper left', fontsize='x-large')
    plt.draw()
    plt.pause(0.001)

def main():
    X = np.loadtxt('data/bunny_target.txt')
    Y = np.loadtxt('data/bunny_source.txt') #synthetic data, equaivalent to X + 1

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    callback = partial(visualize, ax=ax)

    reg = rigid_registration(**{ 'X': X, 'Y': Y })
    reg.register(callback)
    plt.show()

if __name__ == '__main__':
    main()